# Generated by Django 4.0.2 on 2022-03-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_create_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
