# Generated by Django 4.0.2 on 2022-04-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='status',
            field=models.IntegerField(choices=[(0, 'Undo'), (1, 'Done')], default=0, verbose_name='Status'),
        ),
    ]
