# Generated by Django 4.0.2 on 2022-04-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_goals_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
