# Generated by Django 4.0.2 on 2022-04-02 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserICal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=30, verbose_name='Summary')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('start', models.TimeField(verbose_name='Start Time')),
                ('end', models.TimeField(verbose_name='End Time')),
                ('location', models.CharField(max_length=30, verbose_name='Location')),
                ('status', models.IntegerField(choices=[(0, 'Undo'), (1, 'Done')], default=0, verbose_name='Status')),
                ('icsName', models.CharField(blank=True, max_length=200, verbose_name='ICalendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'UserICal',
            },
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=200, verbose_name='Notices')),
                ('user', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Notices',
            },
        ),
    ]
